# Generated by Django 3.1 on 2020-08-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200811_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
