# Generated by Django 3.1 on 2020-08-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200811_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complet',
            field=models.BooleanField(default=False),
        ),
    ]
