# Generated by Django 3.1 on 2020-08-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_complet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complet',
            new_name='complete',
        ),
    ]
