# Generated by Django 3.1 on 2020-08-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20200816_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
